export const statuses = ['Bookmarked','Preparing','Submitted','Under Review','Interview','Awarded','Rejected'] as const;
export type Status = typeof statuses[number];
export type Scholarship = {id:string;name:string;sponsor:string;amount:number;currency:string;deadline:string;status:Status;major:string;level:string;country:string;minGpa:number;gpaScale:number;focus:string;requirements:string;url:string;notes:string;draft:string;tasks:{name:string;done:boolean}[];sample?:boolean};
export type Profile = {name:string;country:string;major:string;level:string;gpa:string;gpaScale:string;activities:string;achievements:string;story:string;essay:string;firstGen:boolean;financialNeed:boolean;tone:string};
export type Notice = {id:string;title:string;body:string;type:'deadline'|'status';date:string;read:boolean;scholarshipId:string};
export type Workspace = {scholarships:Scholarship[];profile:Profile;settings:{intervals:number[];deadline:boolean;status:boolean};notifications:Notice[]};
export const emptyProfile:Profile={name:'',country:'',major:'',level:'',gpa:'',gpaScale:'4',activities:'',achievements:'',story:'',essay:'',firstGen:false,financialNeed:false,tone:'Natural and personal'};
export const blankWorkspace=():Workspace=>({scholarships:[],profile:{...emptyProfile},settings:{intervals:[30,7,2,0],deadline:true,status:true},notifications:[]});
export function daysLeft(date:string,now=new Date()){ const today=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()); return Math.round((Date.parse(date+'T00:00:00Z')-today)/86400000); }
export function dateLabel(date:string){return new Date(date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});}
export function relative(date:string){const n=daysLeft(date);return n<0?`${Math.abs(n)} days overdue`:n===0?'Due today':n===1?'Due tomorrow':`${n} days left`;}
export function sampleScholarships():Scholarship[]{
 const names=[['Future Leaders Scholarship','Meridian Education Foundation',12000,'Preparing','Leadership, community service, first-generation students','Any'],['Women in STEM Fellowship','Northbridge Science Trust',18000,'Preparing','Research, science, mentoring, technology','STEM'],['Community Impact Award','Horizon Giving Fund',5000,'Bookmarked','Volunteering, financial need, community impact','Any'],['Global Scholars Programme','Atlas Learning Foundation',25000,'Submitted','International study, leadership, academic excellence','Any'],['Creative Futures Grant','Studio Education Fund',8000,'Under Review','Design, creative work, storytelling','Arts'],['Research Excellence Award','Whitfield Research Trust',15000,'Bookmarked','Research, innovation, academic achievement','STEM']];
 return names.map((n,i)=>{const d=new Date();d.setUTCDate(d.getUTCDate()+[5,12,21,28,37,45][i]);return {id:'sample-'+i,name:n[0] as string,sponsor:n[1] as string,amount:n[2] as number,currency:'USD',deadline:d.toISOString().slice(0,10),status:n[3] as Status,major:n[5] as string,level:i===5?'Postgraduate':'Any',country:'Any',minGpa:i===1||i===5?3.2:0,gpaScale:4,focus:n[4] as string,requirements:'Write a 500-word personal statement explaining your goals and a specific example of your impact. Include an academic transcript and one recommendation.',url:'',notes:'',draft:'',tasks:[{name:'Personal statement',done:i===3||i===4},{name:'Academic transcript',done:i===0||i===3||i===4},{name:'Recommendation letter',done:i===3||i===4}],sample:true};});
}
export function matching(s:Scholarship,p:Profile){
 const criteria:{label:string;state:'met'|'unmet'|'unknown';detail:string;weight:number}[]=[];
 const add=(label:string,state:'met'|'unmet'|'unknown',detail:string,weight:number)=>criteria.push({label,state,detail,weight});
 if(s.minGpa>0){ const same=Number(p.gpaScale)===s.gpaScale;add('GPA',!p.gpa||!same?'unknown':Number(p.gpa)>=s.minGpa?'met':'unmet',!same?'Different GPA scales: check the sponsor’s conversion policy':`Requires ${s.minGpa}/${s.gpaScale}`,25); }
 if(s.country!=='Any')add('Country',!p.country?'unknown':p.country.toLowerCase()===s.country.toLowerCase()?'met':'unmet',`Eligible country: ${s.country}`,20);
 if(s.level!=='Any')add('Study level',!p.level?'unknown':p.level===s.level?'met':'unmet',`Requires ${s.level}`,20);
 if(s.major!=='Any'){const pm=p.major.toLowerCase();const met=s.major==='STEM'?/science|engineering|math|computer|technology|medicine|biology|physics|chemistry/.test(pm):s.major==='Arts'?/art|design|film|media|creative|literature/.test(pm):pm.includes(s.major.toLowerCase());add('Field of study',!pm?'unknown':met?'met':'unmet',`Focus: ${s.major}`,20);}
 const text=[p.activities,p.achievements,p.story,p.essay,p.firstGen?'first-generation':'',p.financialNeed?'financial need':''].join(' ').toLowerCase();
 const words=[...new Set(s.focus.toLowerCase().split(/\W+/).filter(w=>w.length>4))];const aligned=words.filter(w=>text.includes(w));add('Narrative & activities',!text.trim()?'unknown':aligned.length?'met':'unknown',aligned.length?`Evidence mentions: ${aligned.join(', ')}`:'Add specific achievements and a writing sample to assess fit',15);
 const total=criteria.reduce((n,c)=>n+c.weight,0);const score=total?Math.round(criteria.reduce((n,c)=>n+(c.state==='met'?c.weight:0),0)/total*100):0;
 return {criteria,score,eligible:!criteria.some(c=>c.state==='unmet'),unknown:criteria.some(c=>c.state==='unknown')};
}
export function reminders(w:Workspace){
 const now=new Date().toISOString();for(const s of w.scholarships){if(!w.settings.deadline||['Submitted','Under Review','Interview','Awarded','Rejected'].includes(s.status))continue;const days=daysLeft(s.deadline);if(days<0)continue;
 const eligible=w.settings.intervals.filter(n=>days<=n).sort((a,b)=>a-b);if(!eligible.length)continue;const milestone=eligible[0];const id=`deadline:${s.id}:${s.deadline}:${milestone}`;
 if(!w.notifications.some(n=>n.id===id)){w.notifications.unshift({id,title:`${s.name}: ${relative(s.deadline)}`,body:`Deadline ${dateLabel(s.deadline)}. Check your remaining documents.`,type:'deadline',date:now,read:false,scholarshipId:s.id});}}
 w.notifications=w.notifications.slice(0,200);return w;
}
export function calendar(w:Workspace){const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ScholarSync//Scholarship deadlines//EN','CALSCALE:GREGORIAN'];for(const s of w.scholarships.filter(s=>!['Awarded','Rejected'].includes(s.status))){const day=s.deadline.replaceAll('-','');const end=new Date(s.deadline+'T00:00:00Z');end.setUTCDate(end.getUTCDate()+1);lines.push('BEGIN:VEVENT',`UID:${s.id}@scholarsync`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${day}`,`DTEND;VALUE=DATE:${end.toISOString().slice(0,10).replaceAll('-','')}`,`SUMMARY:${escape(s.name+' deadline')}`,`DESCRIPTION:${escape(s.requirements+'\nConfirm the exact deadline time and timezone with the sponsor.')}`);if(w.settings.deadline)for(const n of w.settings.intervals)lines.push('BEGIN:VALARM',`TRIGGER:${n===0?'PT0S':`-P${n}D`}`,'ACTION:DISPLAY',`DESCRIPTION:${escape(s.name+' deadline reminder')}`,'END:VALARM');lines.push('END:VEVENT');}lines.push('END:VCALENDAR');return lines.join('\r\n')+'\r\n';}
