import {getChatGPTUser} from '@/app/chatgpt-auth';
import {load,save} from '@/lib/store';
import {reminders,sampleScholarships,statuses,type Scholarship,emptyProfile} from '@/lib/scholar';
import {z} from 'zod';
import {env} from 'cloudflare:workers';
const str=z.string().max(20000);const scholarship=z.object({id:z.string().max(100),name:z.string().trim().min(1).max(200),sponsor:z.string().max(200),amount:z.number().min(0).max(1e9),currency:z.enum(['USD','GBP','EUR','NGN','CAD']),deadline:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v),status:z.enum(statuses),major:z.string().max(100),level:z.string().max(100),country:z.string().max(100),minGpa:z.number().min(0).max(5),gpaScale:z.number().min(1).max(5),focus:str,requirements:str,url:z.string().max(2000).refine(v=>!v||/^https?:\/\//.test(v)),notes:str,draft:str,tasks:z.array(z.object({name:z.string().max(200),done:z.boolean()})).max(30),sample:z.boolean().optional()});
const profile=z.object({name:str,country:str,major:str,level:str,gpa:z.string().refine(v=>!v||(Number.isFinite(Number(v))&&Number(v)>=0&&Number(v)<=5)),gpaScale:z.enum(['4','5']),activities:str,achievements:str,story:str,essay:str,firstGen:z.boolean(),financialNeed:z.boolean(),tone:str});
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to load your workspace.'},401);try{const row=await load(user.userId);const before=JSON.stringify(row.workspace.notifications);reminders(row.workspace);if(before!==JSON.stringify(row.workspace.notifications))row.revision=await save(user.userId,row.workspace,row.revision);return reply({...row,aiConnected:!!env.GEMINI_API_KEY});}catch(e){console.error('Workspace read failed',e instanceof Error?e.message:'unknown');return reply({error:'Your workspace could not be loaded. Please retry.'},503);}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to save your work.'},401);if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return reply({error:'Invalid origin'},403);if(Number(request.headers.get('content-length')||0)>300000)return reply({error:'Request is too large'},413);try{const body=z.object({action:z.string(),revision:z.number().int(),scholarship:z.unknown().optional(),profile:z.unknown().optional(),settings:z.unknown().optional()}).parse(await request.json());const row=await load(user.userId);if(body.revision!==row.revision)return reply({error:'This workspace changed in another tab. Reload before saving; your form is still here.'},409);const w=row.workspace;
 if(body.action==='add'){if(w.scholarships.length>=200)throw new Error('LIMIT');const s=scholarship.parse(body.scholarship) as Scholarship;if(w.scholarships.some(x=>x.id===s.id))throw new Error('Duplicate application');w.scholarships.unshift(s);}
 else if(body.action==='update'){const s=scholarship.parse(body.scholarship) as Scholarship;const i=w.scholarships.findIndex(x=>x.id===s.id);if(i<0)return reply({error:'Application not found'},404);const old=w.scholarships[i];if(old.status!==s.status&&w.settings.status)w.notifications.unshift({id:crypto.randomUUID(),title:`${s.name}: ${s.status}`,body:`Application status changed from ${old.status} to ${s.status}.`,type:'status',date:new Date().toISOString(),read:false,scholarshipId:s.id});w.scholarships[i]=s;}
 else if(body.action==='profile'){w.profile=profile.parse(body.profile);if(Number(w.profile.gpa)>Number(w.profile.gpaScale))return reply({error:'GPA exceeds the selected scale'},400);}
 else if(body.action==='settings')w.settings=z.object({intervals:z.array(z.number().int().min(0).max(365)).min(1).max(20),deadline:z.boolean(),status:z.boolean()}).parse(body.settings);
 else if(body.action==='read')w.notifications=w.notifications.map(n=>({...n,read:true}));
 else if(body.action==='samples'){if(w.scholarships.length)return reply({error:'Samples can only be loaded into an empty tracker.'},400);w.scholarships=sampleScholarships();}
 else if(body.action==='clearSamples'){w.scholarships=w.scholarships.filter(s=>!s.sample);w.notifications=w.notifications.filter(n=>!n.scholarshipId.startsWith('sample-'));w.profile=w.profile.name?w.profile:{...emptyProfile};}
 else return reply({error:'Unknown action'},400);
 reminders(w);const revision=await save(user.userId,w,row.revision);return reply({workspace:w,revision,aiConnected:!!env.GEMINI_API_KEY});
 }catch(e){if(e instanceof z.ZodError)return reply({error:'Check the form fields, date, and website URL.'},400);if(e instanceof Error&&e.message==='CONFLICT')return reply({error:'Workspace changed. Reload and try again.'},409);console.error('Workspace save failed',e instanceof Error?e.message:'unknown');return reply({error:'Your changes could not be saved. Your input has been kept; please retry.'},503);}}
